/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyFrames.Mypanels;

import Model.Stocks;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bimalka
 */
public class StockView extends javax.swing.JPanel {
    String url="jdbc:mysql://localhost:3306/els";
    String username="root";
    String password="";
    Connection con=null;
    PreparedStatement pst=null;
    Statement st = null;
    ResultSet rs =null;
    /**
     * Creates new form StockView
     */
    public StockView() {
        initComponents();
        showStocksTable();
    }
    
    public ArrayList<Stocks> stockList(){
        ArrayList<Stocks> StocksList=new ArrayList<>();
        try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            con =(Connection)DriverManager.getConnection(url,username,password);
            String query="SELECT * FROM stocks WHERE qty>0";
            st=(Statement) con.createStatement();
            rs=st.executeQuery(query);
            while(rs.next()){
            Stocks s =new Stocks();
            s.setDescription(rs.getString("description"));
            s.setItemNO(rs.getString("item_number"));
            s.setQty(rs.getInt("qty"));
            StocksList.add(s);
            }
        
        }catch(Exception e){
            System.out.println("Exception -->"+e);
            
        }
        
        return StocksList;
    }
    
    public void showStocksTable(){
    ArrayList<Stocks> list=stockList();
    DefaultTableModel model=(DefaultTableModel)jTable_view_stock_table.getModel();
    Object[] row=new Object[3];
    for(int i=0;i<list.size();i++){
    row[0]=list.get(i).getItemNO();
    row[1]=list.get(i).getDescription();
    row[2]=list.get(i).getQty();
    model.addRow(row);
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_view_stock_table = new javax.swing.JTable();

        setAutoscrolls(true);

        jTable_view_stock_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Number", "Description", "Quantity"
            }
        ));
        jScrollPane1.setViewportView(jTable_view_stock_table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_view_stock_table;
    // End of variables declaration//GEN-END:variables
}
